IF
	InParty("tb#Stiv")
	See("tb#Stiv")
	!StateCheck("tb#Stiv",CD_STATE_NOTVALID)
	Global("FollowedGarren","GLOBAL",1)
	CombatCounter(0)
	Global("tb#StivanKeldornAboutGarren","GLOBAL",0)
	AreaCheck("AR1200")
	!RealGlobalTimerNotExpired("tb#StivanNoSpam","GLOBAL")
THEN
	RESPONSE #80
		RealSetGlobalTimer("tb#StivanNoSpam","GLOBAL",20)
	RESPONSE #20
		RealSetGlobalTimer("tb#StivanNoSpam","GLOBAL",200)
		StartDialogueNoSet("tb#stiv")
END
