IF
	InParty("tb#Stiv")
	See("tb#Stiv")
	!StateCheck("tb#Stiv",CD_STATE_NOTVALID)
	CombatCounter(0)
	GlobalGT("A#IM5Quest","GLOBAL",3)
	Global("tb#StivanMazzyAboutKram","GLOBAL",0)
	!RealGlobalTimerNotExpired("tb#StivanNoSpam","GLOBAL")
THEN
	RESPONSE #80
		RealSetGlobalTimer("tb#StivanNoSpam","GLOBAL",20)
	RESPONSE #20
		RealSetGlobalTimer("tb#StivanNoSpam","GLOBAL",200)
		StartDialogueNoSet("tb#stiv")
END
