// seagull script

IF
	AttackedBy([GOODCUTOFF],DEFAULT)
	!Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		Enemy()
END

IF
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		AttackReevaluate(NearestEnemyOf(Myself),30)
END

IF
	AttackedBy([ANYONE],DEFAULT)
THEN
	RESPONSE #100
		AttackOneRound(LastAttackerOf(Myself))
END


IF
	Delay(5)
	!See(NearestEnemyOf(Myself))
	!AttackedBy([GOODCUTOFF],DEFAULT)
THEN
	RESPONSE #100
		RandomFly()
END

